-- Kiểm tra và xóa cơ sở dữ liệu nếu nó tồn tại
-- DROP DATABASE IF EXISTS CMS_QLCLB;

-- Tạo cơ sở dữ liệu mới
-- CREATE DATABASE CMS_QLCLB;

-- Kết nối tới cơ sở dữ liệu (thực hiện ngoài script SQL)
-- \c CMS_QLCLB

-- TẠO BẢNG
CREATE TABLE "USER_CLB"(
    "MSSV" CHAR(8) PRIMARY KEY,
    "AVATAR" VARCHAR(100),
    "HOTEN" VARCHAR(50),
    "NGAYSINH" DATE,
    "SDT" CHAR(10),
    "EMAIL" VARCHAR(30),
    "DIACHI" VARCHAR(50),
    "BAN" VARCHAR(30),
    "LOP" VARCHAR(10),
    "NGAYVAOCLB" DATE,
    "CHUCVU" INT,
    "MATKHAU" VARCHAR(255),
    "TRANGTHAI" INT
);

CREATE TABLE "TASK"(
    "ID" SERIAL PRIMARY KEY,
    "NGUOITHUCHIEN" CHAR(8),
    "TIEUDE" VARCHAR(255),
    "NOIDUNG" TEXT,
    "NGAYBD" DATE,
    "NGAYTOIHAN" DATE,
    "GHICHU" VARCHAR(255),
    "TRANGTHAI" INT
);

CREATE TABLE "POST"(
    "ID" SERIAL PRIMARY KEY,
    "NGUOIDANG" CHAR(8),
    "TIEUDE" VARCHAR(255),
    "NGAYDANG" DATE,
    "NOIDUNG" TEXT,
    "ANHDINHKEM" VARCHAR(300),
    "LUOTLIKE" INT,
    "LUOTBINHLUAN" INT,
    "TRANGTHAI" INT
);

CREATE TABLE "ACTIVITIES"(
    "ID" SERIAL PRIMARY KEY,
    "NGAYDANG" DATE,
    "NOIDUNG" VARCHAR(255),
    "ANHDINHKEM" VARCHAR(300),

);

CREATE TABLE "CLUB_INFO"(
    "ID" SERIAL PRIMARY KEY,
    "NOIDUNG" TEXT
);

CREATE TABLE "COMMENT"(
    "ID" SERIAL PRIMARY KEY,
    "POSTID" INT,
    "NGUOITHUCHIEN" CHAR(8),
    "NOIDUNG" VARCHAR(255),
    "NGAYCMT" TIMESTAMP
);

CREATE TABLE "LIKES"(
    "POSTID" INT,
    "USERID" CHAR(8),
    PRIMARY KEY("POSTID", "USERID")
);

CREATE TABLE "REFERRAL_CODE" (
    "MSSV" CHAR(8) PRIMARY KEY,
    "MAGIOITHIEU" CHAR(4)
);

-- TẠO KHÓA NGOẠI
ALTER TABLE "TASK"
ADD FOREIGN KEY ("NGUOITHUCHIEN") REFERENCES "USER_CLB"("MSSV");

ALTER TABLE "LIKES"
ADD FOREIGN KEY ("POSTID") REFERENCES "POST"("ID");

ALTER TABLE "LIKES"
ADD FOREIGN KEY ("USERID") REFERENCES "USER_CLB"("MSSV");

ALTER TABLE "POST"
ADD FOREIGN KEY ("NGUOIDANG") REFERENCES "USER_CLB"("MSSV");

ALTER TABLE "COMMENT"
ADD FOREIGN KEY ("POSTID") REFERENCES "POST"("ID");

ALTER TABLE "COMMENT"
ADD FOREIGN KEY ("NGUOITHUCHIEN") REFERENCES "USER_CLB"("MSSV");
